# Book settings
title: Pendata Fahdimas
author: Fahdimas akmal

# Execution settings
execute:
  execute_notebooks: "off"

# Pengaturan HTML
html:
  logo: _static/logo.png  # <--- TAMBAHKAN _static/ di depannya
  favicon: ""
  extra_navbar: ""              # Menghapus navbar tambahan jika ada
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  google_analytics_id: ""       

# Folder tempat gambar berada
# Tambahkan ini agar Jupyter Book memproses folder _static
extra_footer: ""
static_path: ["_static"]

# Repository settings
repository:
  url: https://github.com/Fadimas-Akmal/Pendata
  path_to_book: docs
  branch: main