# Book settings
title: Pendata Fahdimas
author: Fahdimas akmal
copyright: "2022"
logo: profil.png

# Repository settings
repository:
  url: https://github.com/Fahdimas/Pendata
  path_to_book: ""
  branch: main

# Execution settings
execute:
  execute_nb: off

# HTML-specific settings
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  extra_navbar: "Fahdimas Akmal - 240411100228"
  # Bagian ini yang ditambahkan untuk mengaktifkan panah sidebar
  home_page_in_toc: true
  collapse_navigation: true
  show_navbar_depth: 1

# Parse settings
parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - tasklist