# Book settings
title: Pendata Fadimas
author: Fahdimas Sakmal

# Execution settings
execute:
  execute_notebooks: "off"

# Pengaturan HTML (Logo profil normal tanpa edit CSS)
html:
  logo: logo.png

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Fadimas-Akmal/Pendata
  path_to_book: docs
  branch: main